name: CI/CD Pipeline
run-name: ${{ github.actor }}'s CI/CD Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - "ga-ignore-"

jobs:
  build:
    name: 🛠️ Build
    runs-on: self-hosted
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v1

      - run: |
          docker build -t internet_lost:latest .

  build_docker_images:
    name: 🛠️ Build Docker images
    runs-on: self-hosted
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v1

      - run: |
          docker build -t internet_lost:latest .

  push_docker_images:
    name: 📡 Push Docker images to Docker Hub
    runs-on: self-hosted
    needs: build_docker_images
    if: github.event_name == 'push'

    steps:
      - run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag internet_lost:latest ${{ secrets.DOCKERHUB_USERNAME }}/whatsup:internet_lost
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/whatsup:internet_lost

  deploy:
    name: 🚀 Deploy to VPS
    runs-on: self-hosted
    needs: push_docker_images
    if: github.event_name == 'push'

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_APP_DIR }}
            sudo docker container stop internet_lost || true
            sudo docker container rm internet_lost || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/whatsup:internet_lost
            sudo docker compose up -d
